
GET http://localhost:8080/blog/list

###

POST http://localhost:8080/blog/save
Content-Type: application/json

{
  "authorId": 171897790761406464,
  "content": "<p>hello</p>"
}

###
GET http://localhost:8080/blog/listByPage/2/10

###

GET http://localhost:8080/blog/blogNum

###