GET http://localhost:8080/hello
#Accept: application/json

###

POST http://localhost:8080/user/signup
Content-Type: application/json

{
"username": "big2",
"name": "萝卜2",
"password": "123"
}

###
POST http://localhost:8080/user/login
Content-Type: application/json

{
"username": "big2",
"password": "123"
}

###
POST http://localhost:8080/user/updateInfo
Content-Type: application/json

{
  "id": "171897790761406464",
  "selfIntro": "一千年前的萝卜种子",
  "age": 18,
  "gender": "male",
  "circles": "{'吉他社','读书会'}",
  "managedCircles": "{'吉他社'}",
  "tags": "",
  "status": false
}

###

GET http://localhost:8080/user/info/171897790761406464

###
GET http://localhost:8080/user/list

###

GET http://localhost:8880/test/redis/set/123/test
Accept: application/json

###

GET http://localhost:8880/redis/get/15271595887169536
Accept: application/json

###
